version: '3.7'
services:
  postgres:
    image: postgres:12
    container_name: 6string_postgres
    ports:
      - 5432:5432
    env_file:
      - ./api/.env
  client:
    container_name: 6string_client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 5000:5000
  api:
    depends_on:
      - postgres
    container_name: 6string_api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 4000:4000


