version: '3.7'
services:
  postgresprod:
    image: postgres:12
    container_name: postgresprod
    ports:
      - 5432:5432
    env_file:
      - ./api/.env
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 5000:5000
  api:
    depends_on:
      - postgresprod
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 3000:3000
    command: bash -c "yarn workspace api run prisma:reset && yarn workspace api run start:prod"



