FROM node:14-alpine
# RUN apk update && apk add bash

EXPOSE 4000

COPY . ./
COPY ./api/.env.prod ./api/.env
COPY ./api/prisma/.env.prod ./api/prisma/.env
RUN yarn install
RUN yarn workspace api run prisma generate
RUN yarn workspace api run build

CMD [ "yarn", "workspace", "api", "start:prod" ]
